name: Feature
description: Suggest an idea
body:
- type: markdown
  attributes:
    value: |-
      ### ⚠️ WARNING
      
      Half of all issues created do not contain enough to help or are not appropriate for the issue tracker (i.e. one-line questions).
      If you would like to suggest a feature, follow the steps outlined below closely.
      Any issue that does not meet these conditions may be closed unnoticed.
      
      Why? Because the maintainers of this project are wasting a lot of time answering questions that are not directly related to this project.
      If you have a question, please ask your question over in [Discussions](https://github.com/squidfunk/mkdocs-material/discussions), so other users can help you work towards a solution.
- type: checkboxes
  attributes:
    label: Read and understand the Contributing guidelines
    description: You need to have read the contributing guidelines in order to proceed.
    options:
    - label: I've read the [contribution Guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and agree with them
      required: true
- type: checkboxes
  attributes:
    label: I want to suggest an idea and checked that ...
    description: Make sure that your request fulfills ALL of the following requirements. If one requirement cannot be satisfied, please explain in detail why.
    options:
    - label: ... to my best knowledge, my idea wouldn't break something for other users
    - label: ... the documentation does not mention anything about my idea
    - label: ... there are no open or closed issues that are related to my idea
- type: textarea
  attributes:
    label: Description
    description: Please provide a breif description of the bug.
    placeholder: My feature would ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Use Cases
    description: Please describe how your suggestion would benefit you and other users.
    placeholder: My feature is beneficial because ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots / Mockups
    description: If applicable, provide some mockups or screenshots.
    placeholder: "https://i.imgur.com/cat.jpg"
